bayesCor optionNames - NOT YET TESTED
jasp-stats/jaspRegression pull request #151
Opened 2022-08-16 10:06 UTC by AlexanderLyNL

2022-08-17 15:11 UTC, AlexanderLyNL commented
So after updating the packages as recommended by Don, I get the same error message as on GitHub actions. 

Note that I've edited `CorrelationBayesian` but not `Correlation`. The unit test fails oddly in the sense that browser (`jaspResults[["mainTable"]]$print()` and `jaspResults[["mainTable"]]$printHtml()` gives me something else than the html. 

```
results <- jaspTools::runAnalysis("Correlation", "debug.csv", options)

## browser() statement before return()

Browse[2]> jaspResults[["mainTable"]]$print()
table Correlation Table:
	status: running
	                                                              
	                                 contNormal    contGamma   
	                               |-------------|------------|
	Variable var1             | contNormal  | contGamma  |
	                               |-------------|------------|
	              n                | —         |            |
	                               |-------------|------------|
	              Pearson's r      | —         |            |
	                               |-------------|------------|
	              p-value          | —         |            |
	                               |-------------|------------|
	              VS-MPR           | —         |            |
	                               |-------------|------------|
	              Upper 95% CI     | —         |            |
	                               |-------------|------------|
	              Lower 95% CI     | —         |            |
	                               |-------------|------------|
	              Spearman's rho   | —         |            |
	                               |-------------|------------|
	              p-value          | —         |            |
	                               |-------------|------------|
	              VS-MPR           | —         |            |
	                               |-------------|------------|
	              Upper 95% CI     | —         |            |
	                               |-------------|------------|
	              Lower 95% CI     | —         |            |
	                               |-------------|------------|
	              Kendall's Tau B  | —         |            |
	                               |-------------|------------|
	              p-value          | —         |            |
	                               |-------------|------------|
	              VS-MPR           | —         |            |
	                               |-------------|------------|
	              Upper 95% CI     | —         |            |
	                               |-------------|------------|
	              Lower 95% CI     | —         |            |
	                               |-------------|------------|
	              n                | 100         | —        |
	                               |-------------|------------|
	              Pearson's r      | -5.9200e-02 | —        |
	                               |-------------|------------|
	              p-value          | 0.558       | —        |
	                               |-------------|------------|
	              VS-MPR           | 1.0000e+00  | —        |
	                               |-------------|------------|
	              Upper 95% CI     | 1.3883e-01  | —        |
	                               |-------------|------------|
	              Lower 95% CI     | -2.5268e-01 | —        |
	                               |-------------|------------|
	              Spearman's rho   | -3.4179e-02 | —        |
	                               |-------------|------------|
	              p-value          | 0.735       | —        |
	                               |-------------|------------|
	              VS-MPR           | 1.0000e+00  | —        |
	                               |-------------|------------|
	              Upper 95% CI     | 1.6334e-01  | —        |
	                               |-------------|------------|
	              Lower 95% CI     | -2.2906e-01 | —        |
	                               |-------------|------------|
	              Kendall's Tau B  | -2.6667e-02 | —        |
	                               |-------------|------------|
	              p-value          | 0.694       | —        |
	                               |-------------|------------|
	              VS-MPR           | 1.0000e+00  | —        |
	                               |-------------|------------|
	              Upper 95% CI     | 9.7081e-02  | —        |
	                               |-------------|------------|
	              Lower 95% CI     | -1.5041e-01 | —        |
	                               |-------------|------------|
```

but I get the following output: 

<img width="694" alt="Screenshot 2022-08-17 at 17 08 40" src="https://user-images.githubusercontent.com/10271675/185175494-a0f9e1af-22bd-47e4-a274-a1f1f8d3ea0f.png">

2022-08-22 16:23 UTC, Kucharssim requested changes
Looks good, just a couple of suggestions. Also, please rename `ciValue` -> `ciLevel`

2022-08-22 16:23 UTC, Kucharssim commented on inst/qml/CorrelationBayesian.qml
> +        CheckBox {	name: "sampleSizeReport";               label: qsTr("Sample size")								}
should this be just `sampleSize` for consistency with classical corrs?

2022-08-22 16:23 UTC, Kucharssim commented on R/correlationbayesian.R
> +        v2 <- dataset[[jaspBase::encodeColNames(var2)]]
are you sure you need the encoding at all? assuming `var1` and `var2` come from an options list, they should be already encoded by JASP.

2022-08-22 16:23 UTC, Kucharssim commented on inst/Upgrades.qml
> +                    case "two.sided":				return "twoSided"	;
here the upgrader fails, as you need to put in the default option:

```suggestion
                    case "two.sided":				return "twoSided"	;
                    default:						return options["alternative"];
```

2022-08-22 16:23 UTC, Kucharssim commented on inst/Upgrades.qml
> +    Upgrade
the formatting in this upgrade is inconsistent (replace spaces with tabs)

2022-08-23 10:46 UTC, Kucharssim approved these changes

2022-08-23 10:47 UTC, merged