renamed options for logistic regression
jasp-stats/jaspRegression pull request #160
Opened 2022-08-29 13:33 UTC by fqixiang

fixed https://github.com/jasp-stats/INTERNAL-jasp/issues/1938

2022-09-09 12:26 UTC, Kucharssim requested changes
looks great, minor suggestions

2022-09-09 12:26 UTC, Kucharssim commented on inst/qml/RegressionLogistic.qml
> +			CheckBox { name: "descriptive"; label: qsTr("Factor descriptives") }
same as in linear regression

2022-09-09 12:26 UTC, Kucharssim commented on inst/qml/RegressionLogistic.qml
> +				CheckBox { name: "robustStandardError";		label: qsTr("Robust standard errors")	}
```suggestion
				CheckBox { name: "robustSe";		label: qsTr("Robust standard errors")	}
```

2022-09-30 12:06 UTC, Kucharssim requested changes
looks good! just bump the version in upgrades, fix the conflicts, and it can be merged!

2022-09-30 12:06 UTC, Kucharssim commented on inst/Upgrades.qml
> +		toVersion:			"0.16.4"
```suggestion
		fromVersion:		"0.16.4"
		toVersion:			"0.17.0"
```

2022-10-03 16:24 UTC, fqixiang commented
Not so sure why why of the tests failed. Any idea, Simon?

2022-10-04 12:18 UTC, Kucharssim approved these changes
Looks good now; the tests fail on Ubuntu but that's because jaspBase is currently broken there. Nothing to worry about wrt this PR

2022-10-04 12:19 UTC, merged